# Generated by Django 4.1.4 on 2023-01-10 10:34

import OrderApp.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logindb",
            fields=[
                (
                    "sState",
                    models.CharField(
                        default=OrderApp.models.wStateUUID,
                        max_length=43,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Rstate", models.CharField(max_length=42)),
                ("RuserID", models.CharField(max_length=43)),
                ("RSMSid", models.CharField(max_length=42)),
                ("sPhone", models.CharField(max_length=10)),
                ("Raccess_code", models.CharField(max_length=43)),
                ("sTime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Login紀錄",
                "verbose_name_plural": "Login紀錄",
            },
        ),
        migrations.CreateModel(
            name="OrderRecord",
            fields=[
                (
                    "sOrderID",
                    models.CharField(
                        default=OrderApp.models.sOrderIDUUID,
                        max_length=42,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sUserID", models.CharField(max_length=43)),
                ("sSum", models.FloatField()),
                ("sPoint", models.FloatField()),
                ("sCarbon", models.FloatField()),
                ("sWash", models.CharField(max_length=5)),
                ("sDry", models.CharField(max_length=4)),
                ("sFold", models.CharField(max_length=5)),
                ("sOrderType", models.CharField(max_length=6)),
                ("sCreateTime", models.DateTimeField(default=datetime.datetime.now)),
                ("sFinishTime", models.DateTimeField(null=True)),
                ("sStoreName", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "訂單記錄",
                "verbose_name_plural": "訂單記錄",
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sOrderID", models.CharField(max_length=32)),
                ("sSentTime", models.DateTimeField(default=datetime.datetime.now)),
                ("sDirections", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "問題回報",
                "verbose_name_plural": "問題回報",
            },
        ),
        migrations.CreateModel(
            name="QRcode",
            fields=[
                (
                    "sOrderID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sCodeA", models.CharField(max_length=20)),
                ("sCodeB", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "QRcode",
                "verbose_name_plural": "QRcode",
            },
        ),
        migrations.CreateModel(
            name="Satisfy",
            fields=[
                (
                    "sOrderID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sServe", models.BooleanField(null=True)),
                ("sRate", models.BooleanField(null=True)),
                ("sSatisfy", models.BooleanField(null=True)),
            ],
            options={
                "verbose_name": "滿意度",
                "verbose_name_plural": "滿意度",
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "sUserID",
                    models.CharField(max_length=43, primary_key=True, serialize=False),
                ),
                ("sBag", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "顧客資料",
                "verbose_name_plural": "顧客資料",
            },
        ),
        migrations.CreateModel(
            name="UserMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sListName", models.CharField(max_length=20)),
                ("sWash", models.CharField(max_length=10)),
                ("sDry", models.CharField(max_length=10)),
                ("sFold", models.CharField(max_length=10)),
                (
                    "sUserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OrderApp.userdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "常用洗衣模式列表",
                "verbose_name_plural": "常用洗衣模式列表",
            },
        ),
    ]
