# Generated by Django 3.2.5 on 2022-12-23 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('sUserID', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('sOrderID', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='訂單編號')),
                ('sSum', models.FloatField(verbose_name='總金額')),
                ('sPoint', models.FloatField(verbose_name='總點數')),
                ('sDeliveryID', models.CharField(max_length=32, null=True, verbose_name='外送編號')),
                ('sCreateTime', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='成立時間')),
                ('sFinishTime', models.DateTimeField(null=True, verbose_name='完成時間')),
                ('sStoreName', models.CharField(blank=True, max_length=10, verbose_name='店鋪名稱')),
                ('sUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderApp.userdata', verbose_name='使用者編號')),
            ],
            options={
                'verbose_name': '訂單記錄',
                'verbose_name_plural': '訂單記錄',
            },
        ),
    ]
