# Generated by Django 4.1.4 on 2022-12-27 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Common",
            fields=[
                (
                    "sCommonID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sListName", models.CharField(max_length=10)),
                ("sWash", models.PositiveIntegerField()),
                ("sDry", models.PositiveIntegerField()),
                ("sFold", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "常用洗衣模式列表",
                "verbose_name_plural": "常用洗衣模式列表",
            },
        ),
        migrations.CreateModel(
            name="Mode",
            fields=[
                (
                    "sOrderID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sWash", models.PositiveIntegerField()),
                ("sDry", models.PositiveIntegerField()),
                ("sFold", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "訂單洗衣設定",
                "verbose_name_plural": "訂單洗衣設定",
            },
        ),
        migrations.CreateModel(
            name="ModeMenu",
            fields=[
                (
                    "sModeID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sModeName", models.CharField(max_length=10)),
                ("sTime", models.TimeField()),
                ("sAmount", models.FloatField()),
                ("sPPoint", models.FloatField()),
            ],
            options={
                "verbose_name": "洗衣模式價格表",
                "verbose_name_plural": "洗衣模式價格表",
            },
        ),
        migrations.CreateModel(
            name="OrderRecord",
            fields=[
                (
                    "sOrderID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sUserID", models.CharField(max_length=32)),
                ("sSum", models.FloatField()),
                ("sPoint", models.FloatField()),
                (
                    "sCreateTime",
                    models.DateTimeField(default=datetime.datetime.now, null=True),
                ),
                ("sFinishTime", models.DateTimeField(null=True)),
                ("sStoreName", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "訂單記錄",
                "verbose_name_plural": "訂單記錄",
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "sProblemID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sOrderID", models.CharField(max_length=32)),
                ("sSentTime", models.DateTimeField(default=datetime.datetime.now)),
                ("sDirections", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "問題回報",
                "verbose_name_plural": "問題回報",
            },
        ),
        migrations.CreateModel(
            name="QRcode",
            fields=[
                (
                    "sOrderID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sCodeA", models.CharField(max_length=20)),
                ("sCodeB", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "QRcode",
                "verbose_name_plural": "QRcode",
            },
        ),
        migrations.CreateModel(
            name="Satisfy",
            fields=[
                (
                    "sOrderID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sServe", models.BooleanField()),
                ("sRate", models.BooleanField()),
                ("sSatisfy", models.BooleanField()),
            ],
            options={
                "verbose_name": "滿意度",
                "verbose_name_plural": "滿意度",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "sStoreID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sStoreName", models.CharField(max_length=10)),
                ("sStoreAdd", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "店鋪",
                "verbose_name_plural": "店鋪",
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "sUserID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sBag", models.PositiveIntegerField(default=0)),
                ("sUserMode", models.PositiveIntegerField(null=True)),
            ],
            options={
                "verbose_name": "顧客資料",
                "verbose_name_plural": "顧客資料",
            },
        ),
    ]
