# Generated by Django 4.1.4 on 2023-01-11 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="sReciveTime",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="sTakeTime",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
