# Generated by Django 4.1.4 on 2022-12-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sUserID", models.CharField(max_length=32)),
                ("sListName", models.CharField(max_length=10)),
                ("sWash", models.PositiveIntegerField()),
                ("sDry", models.PositiveIntegerField()),
                ("sFold", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "常用洗衣模式列表",
                "verbose_name_plural": "常用洗衣模式列表",
            },
        ),
        migrations.DeleteModel(
            name="Common",
        ),
    ]
