# Generated by Django 4.1.4 on 2022-12-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderRecord",
        ),
        migrations.DeleteModel(
            name="UserData",
        ),
    ]
