# Generated by Django 4.1.4 on 2022-12-26 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("OrderApp", "0002_delete_orderrecord_delete_userdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mode",
            fields=[
                (
                    "sModeID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("sUserID", models.CharField(max_length=32, verbose_name="使用者編號")),
                ("sWash", models.PositiveIntegerField(verbose_name="洗衣模式編號")),
                ("sDry", models.PositiveIntegerField(verbose_name="烘衣模式編號")),
                ("sFold", models.PositiveIntegerField(verbose_name="折衣模式編號")),
            ],
            options={
                "verbose_name": "訂單洗衣設定",
                "verbose_name_plural": "訂單洗衣設定",
            },
        ),
        migrations.CreateModel(
            name="OrderRecord",
            fields=[
                (
                    "sOrderID",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="訂單編號",
                    ),
                ),
                ("sUserID", models.CharField(max_length=32, verbose_name="使用者編號")),
                ("sSum", models.FloatField(verbose_name="總金額")),
                ("sPoint", models.FloatField(verbose_name="總點數")),
                (
                    "sDeliveryID",
                    models.CharField(max_length=32, null=True, verbose_name="外送編號"),
                ),
                (
                    "sCreateTime",
                    models.DateTimeField(
                        default=datetime.datetime.now, null=True, verbose_name="成立時間"
                    ),
                ),
                ("sFinishTime", models.DateTimeField(null=True, verbose_name="完成時間")),
                (
                    "sStoreName",
                    models.CharField(blank=True, max_length=10, verbose_name="店鋪名稱"),
                ),
            ],
            options={
                "verbose_name": "訂單記錄",
                "verbose_name_plural": "訂單記錄",
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "sUserID",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="使用者編號",
                    ),
                ),
                (
                    "sBag",
                    models.PositiveIntegerField(default=0, verbose_name="持有洗衣袋數量"),
                ),
                (
                    "sUserMode",
                    models.PositiveIntegerField(null=True, verbose_name="常用洗衣模式編號"),
                ),
                (
                    "sUserAddress",
                    models.PositiveIntegerField(null=True, verbose_name="常用地址編號"),
                ),
            ],
            options={
                "verbose_name": "顧客資料",
                "verbose_name_plural": "顧客資料",
            },
        ),
    ]
