# Generated by Django 4.1.4 on 2022-12-27 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0002_usermode_delete_common"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mode",
        ),
        migrations.RenameField(
            model_name="modemenu",
            old_name="sAmount",
            new_name="sPrice",
        ),
        migrations.RemoveField(
            model_name="modemenu",
            name="sModeID",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="sProblemID",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="sUserMode",
        ),
        migrations.AddField(
            model_name="modemenu",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=7.020833333333333,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderrecord",
            name="sDry",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderrecord",
            name="sFold",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderrecord",
            name="sWash",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="problem",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="modemenu",
            name="sTime",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="orderrecord",
            name="sCreateTime",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="problem",
            name="sDirections",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="usermode",
            name="sDry",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="usermode",
            name="sFold",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="usermode",
            name="sListName",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="usermode",
            name="sUserID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="OrderApp.userdata"
            ),
        ),
        migrations.AlterField(
            model_name="usermode",
            name="sWash",
            field=models.CharField(max_length=10),
        ),
    ]
