# Generated by Django 4.1.4 on 2023-01-11 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0002_delivery_srecivetime_delivery_staketime"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="sAddress",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
