# Generated by Django 4.1.4 on 2022-12-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0003_delete_mode_rename_samount_modemenu_sprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modemenu",
            name="sPPoint",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="modemenu",
            name="sPrice",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="modemenu",
            name="sTime",
            field=models.DurationField(null=True),
        ),
    ]
