# Generated by Django 4.1.4 on 2023-01-11 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0003_delivery_saddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery_state",
            name="cline_display",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
