# Generated by Django 4.1.4 on 2022-12-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeMenu",
            fields=[
                (
                    "sModeID",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                (
                    "sModeName",
                    models.CharField(blank=True, max_length=10, verbose_name="模式名稱"),
                ),
                ("sWash", models.TimeField(verbose_name="所需時間")),
                ("sAmount", models.FloatField(verbose_name="價格")),
                ("sPPoint", models.FloatField(verbose_name="點數")),
            ],
            options={
                "verbose_name": "訂單洗衣設定",
                "verbose_name_plural": "訂單洗衣設定",
            },
        ),
        migrations.CreateModel(
            name="store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sUserID", models.CharField(max_length=32, verbose_name="使用者編號")),
                (
                    "sStoreName",
                    models.CharField(blank=True, max_length=10, verbose_name="店鋪名稱"),
                ),
                (
                    "sStoreAdd",
                    models.CharField(blank=True, max_length=100, verbose_name="店鋪地址"),
                ),
            ],
            options={
                "verbose_name": "店鋪",
                "verbose_name_plural": "店鋪",
            },
        ),
        migrations.RenameField(
            model_name="mode",
            old_name="sModeID",
            new_name="sStoreID",
        ),
    ]
