# Generated by Django 4.1.4 on 2022-12-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0004_alter_modemenu_sppoint_alter_modemenu_sprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modemenu",
            name="sTime",
            field=models.DateField(null=True),
        ),
    ]
