# Generated by Django 4.1.4 on 2022-12-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0004_modemenu_store_rename_smodeid_mode_sstoreid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mode",
            old_name="sStoreID",
            new_name="sModeID",
        ),
    ]
