# Generated by Django 4.1.4 on 2023-01-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0004_delivery_state_cline_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="sReciveTime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="sTakeTime",
            field=models.DateTimeField(),
        ),
    ]
