# Generated by Django 4.1.4 on 2023-01-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0005_alter_delivery_srecivetime_alter_delivery_staketime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery_state",
            options={"verbose_name": "外送單代碼", "verbose_name_plural": "外送單代碼"},
        ),
    ]
