# Generated by Django 4.1.4 on 2022-12-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0005_alter_modemenu_stime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modemenu",
            name="sTime",
            field=models.DurationField(null=True),
        ),
    ]
