# Generated by Django 4.1.4 on 2022-12-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0006_alter_modemenu_stime"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModeMenu",
        ),
        migrations.DeleteModel(
            name="Store",
        ),
    ]
