# Generated by Django 4.1.4 on 2022-12-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0007_delete_modemenu_delete_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="satisfy",
            name="sRate",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="satisfy",
            name="sSatisfy",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="satisfy",
            name="sServe",
            field=models.BooleanField(null=True),
        ),
    ]
