# Generated by Django 4.1.4 on 2023-01-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0008_alter_satisfy_srate_alter_satisfy_ssatisfy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderrecord",
            name="sDry",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="orderrecord",
            name="sFold",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="orderrecord",
            name="sWash",
            field=models.CharField(max_length=6),
        ),
    ]
