# Generated by Django 4.1.4 on 2023-01-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0008_delivery_swashtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="sDelivery_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="delivery_notecline_display",
                to="OrderApp.delivery_state",
            ),
        ),
    ]
