# Generated by Django 4.1.4 on 2023-01-11 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0009_alter_delivery_sdelivery_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderrecord",
            name="sFinish",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="sDelivery_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="delivery_note",
                to="OrderApp.delivery_state",
            ),
        ),
    ]
