# Generated by Django 4.1.4 on 2023-01-07 21:01

import OrderApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0009_alter_orderrecord_sdry_alter_orderrecord_sfold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineLogin",
            fields=[
                (
                    "sState",
                    models.CharField(
                        default=OrderApp.models.wStateUUID,
                        max_length=43,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Rstate", models.CharField(max_length=42)),
                ("Raccess_code", models.CharField(max_length=43)),
                ("sTime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "lineLogin紀錄",
                "verbose_name_plural": "lineLogin紀錄",
            },
        ),
        migrations.AlterField(
            model_name="orderrecord",
            name="sDry",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="orderrecord",
            name="sFold",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="orderrecord",
            name="sWash",
            field=models.CharField(max_length=4),
        ),
    ]
