# Generated by Django 4.1.4 on 2023-01-07 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0010_linelogin_alter_orderrecord_sdry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linelogin",
            name="RuserID",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 1, 7, 22, 17, 34, 187941, tzinfo=datetime.timezone.utc
                ),
                max_length=43,
            ),
            preserve_default=False,
        ),
    ]
