# Generated by Django 4.1.4 on 2023-01-08 15:10

import OrderApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0011_linelogin_ruserid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logindb",
            fields=[
                (
                    "sState",
                    models.CharField(
                        default=OrderApp.models.wStateUUID,
                        max_length=43,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Rstate", models.CharField(max_length=42)),
                ("RuserID", models.CharField(max_length=43)),
                ("RSMSid", models.CharField(max_length=42)),
                ("sphone", models.CharField(max_length=10)),
                ("Raccess_code", models.CharField(max_length=43)),
                ("sTime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "lineLogin紀錄",
                "verbose_name_plural": "lineLogin紀錄",
            },
        ),
        migrations.DeleteModel(
            name="LineLogin",
        ),
    ]
