# Generated by Django 4.1.4 on 2023-01-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0012_logindb_delete_linelogin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logindb",
            old_name="sphone",
            new_name="sPhone",
        ),
    ]
