# Generated by Django 4.1.4 on 2023-01-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderApp", "0013_rename_sphone_logindb_sphone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logindb",
            options={"verbose_name": "Login紀錄", "verbose_name_plural": "Login紀錄"},
        ),
        migrations.AlterField(
            model_name="orderrecord",
            name="sUserID",
            field=models.CharField(max_length=43),
        ),
        migrations.AlterField(
            model_name="orderrecord",
            name="sWash",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="sUserID",
            field=models.CharField(max_length=43, primary_key=True, serialize=False),
        ),
    ]
