# Generated by Django 4.1.4 on 2022-12-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBmanageApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modemenu",
            name="sCarbon",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="modemenu",
            name="sModeName",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
