# Generated by Django 4.1.4 on 2023-01-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBmanageApp", "0002_modemenu_scarbon_alter_modemenu_smodename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modemenu",
            name="sModeName",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
